global:
  application_name: CLARK
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.3.0
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  workspace_type: Application
deploy:
  artifact: /tmp/dist.zip
